Update ShapeObstacleCalculator.ts to import Node
When building a library which uses @msagl/core I get the following error:

```
../../node_modules/@msagl/core/dist/routing/ShapeObstacleCalculator.d.ts:10:46 - error TS2304: Cannot find name 'Node'.

10     loosePolylinesToNodes: Map<Polyline, Set<Node>>;
                                                ~~~~


Found 1 error in ../../node_modules/@msagl/core/dist/routing/ShapeObstacleCalculator.d.ts:10
```

There's a reference to `Node` in `ShapeObstacleCalculator` that isn't imported in the actual file.  Additionally, without this import, VSCode assumes Node is the one from the TS DOM.